_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "FC7GenRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "FC7ROIHeads"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
